# Generated by Django 4.2.13 on 2025-08-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='Cars/')),
                ('v_name', models.TextField()),
                ('seats', models.CharField(choices=[('0', '4'), ('1', '5'), ('2', '7')], default='1', max_length=10)),
                ('vehicle_type', models.CharField(choices=[('SUVs', 'SUVs'), ('Sedans', 'Sedans'), ('Crossovers', 'Crossovers'), ('Coupes', 'Coupes'), ('Hatchbacks', 'Hatchbacks')], default='1', max_length=50)),
                ('stock_no', models.TextField(unique=True)),
                ('doors', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('VIN', models.TextField(unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(null=True)),
                ('make', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('0', 'Unavailable'), ('1', 'Available')], default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ourgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_img', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('c_fullcode', models.TextField()),
                ('c_createddate', models.DateField(auto_now_add=True)),
                ('c_type', models.CharField(max_length=255)),
                ('c_required', models.TextField()),
                ('c_des', models.TextField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeapp.category')),
            ],
        ),
    ]
